import { Card, Badge, ArithmeticQuestion, KanjiQuestion } from './types';

export const DEFAULT_CARDS: Card[] = [
  // Normal Cards (10-30 coins value range)
  {
    id: 'n1',
    name: 'ピカポチ',
    rarity: 'N',
    description: 'いつも元気に飛び跳ねている、でんきネズミ。ほっぺたを触ると静電気がピリリと走るよ。勉強が大好き！',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n2',
    name: 'モリノコ',
    rarity: 'N',
    description: '森の奥深くに住んでいる葉っぱの妖精。読書が趣味で、漢字を覚えるのが得意なんだ。',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n3',
    name: 'ペンタロウ',
    rarity: 'N',
    description: 'お腹の星マークがチャームポイントのペンギン。算数の計算を始めるとスピードが止まらない！',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n4',
    name: 'コロリン',
    rarity: 'N',
    description: 'ころころ転がる不思議な岩石モンスター。数字の「0」が大好きで、わり算を応援してくれる。',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n5',
    name: 'ウサノフ',
    rarity: 'N',
    description: 'ノートを抱えたウサギ。いつも勉強の予定をメモしている、しっかり者。',
    imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=1200&auto=format&fit=crop&q=80',
  },
  // Rare Cards
  {
    id: 'r1',
    name: 'イナズマレオ',
    rarity: 'R',
    description: '雲の上を走る、雷の力を持つちいさなライオン。算数の「かけ算筆算」で稲妻のような速さを手に入れた！',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r2',
    name: 'ホシヨミフクロウ',
    rarity: 'R',
    description: '夜空の星を読んで未来を占うフクロウ。漢字の歴史をすべて知っている物知り博士。',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r3',
    name: 'アクアドフィン',
    rarity: 'R',
    description: 'きれいな水の世界を守るイルカ。分数の計算が得意で、ピザやケーキを等分するのが大好き。',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r4',
    name: 'クリスタルキツネ',
    rarity: 'R',
    description: '結晶のような美しいしっぽを持つキツネ。集中力が高まると、体が青くきらめくよ。',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
  },
  // Super Rare Cards
  {
    id: 'sr1',
    name: 'フェニックス・マスタリー',
    rarity: 'SR',
    description: 'あきらめずに挑戦し続けた勉強者にのみ姿を現す不死鳥。すべてを包み込む暖かい光で満ちている。',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'sr2',
    name: 'ギャラクシードラゴン',
    rarity: 'SR',
    description: '銀河のエネルギーを宿した伝説のドラゴン。大きな数（億兆）を自由に操り、宇宙を旅する。',
    imageUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'sr3',
    name: 'エンプレス・サクラ',
    rarity: 'SR',
    description: '漢字の奥義を極めた美しい桜の精霊。流れるような筆さばきで、すべての漢字を美しく書き上げる。',
    imageUrl: 'https://images.unsplash.com/photo-1522441815192-d9f04eb0615c?w=1200&auto=format&fit=crop&q=80',
  }
];

export const DEFAULT_BADGES: Badge[] = [
  {
    id: 'badge_1',
    name: 'はじめの一歩',
    description: '最初の勉強をクリアする',
    iconName: 'BookOpen',
    requiredStreak: 0,
    unlocked: false,
  },
  {
    id: 'badge_2',
    name: '3日連続の達人',
    description: '勉強を3日間連続でがんばる',
    iconName: 'Flame',
    requiredStreak: 3,
    unlocked: false,
  },
  {
    id: 'badge_3',
    name: '5日連続の英雄',
    description: '勉強を5日間連続でがんばる',
    iconName: 'Award',
    requiredStreak: 5,
    unlocked: false,
  },
  {
    id: 'badge_4',
    name: '1週間マスター',
    description: '勉強を7日間連続でがんばる',
    iconName: 'Trophy',
    requiredStreak: 7,
    unlocked: false,
  },
  {
    id: 'badge_5',
    name: 'コレクター',
    description: 'トレーディングカードを5枚以上集める',
    iconName: 'Grid',
    requiredStreak: 0,
    unlocked: false,
  }
];

// 3rd Grade Arithmetic Questions
export const ARITHMETIC_QUESTIONS: ArithmeticQuestion[] = [
  // わり算 (Division)
  {
    id: 'm1',
    num1: 24,
    num2: 4,
    operator: '÷',
    questionText: '24 ÷ 4 はいくつかな？（4のだんの九九を思い出してね）',
    correctAnswer: 6,
    options: [4, 5, 6, 8],
    hint: '「4に何をかけたら24になるかな？」と考えてみてね。',
  },
  {
    id: 'm2',
    num1: 35,
    num2: 5,
    operator: '÷',
    questionText: '35 ÷ 5 はいくつかな？',
    correctAnswer: 7,
    options: [5, 6, 7, 8],
    hint: '5の段の九九で、答えが35になるものをさがそう！',
  },
  {
    id: 'm3',
    num1: 48,
    num2: 8,
    operator: '÷',
    questionText: '48 ÷ 8 はいくつかな？',
    correctAnswer: 6,
    options: [5, 6, 7, 8],
    hint: '8 × [ ] = 48。あてはまる数字は何かな？',
  },
  {
    id: 'm4',
    num1: 0,
    num2: 9,
    operator: '÷',
    questionText: '0 ÷ 9 はいくつかな？（お菓子が0個のとき、9人で分けても…？）',
    correctAnswer: 0,
    options: [0, 1, 9, 3],
    hint: '何もないものを分けても、やっぱり0だね！',
  },

  // かけ算筆算 (Multiplication with carry over)
  {
    id: 'm5',
    num1: 23,
    num2: 3,
    operator: '×',
    questionText: '23 × 3 はいくつかな？（筆算のように、一の位から順番にかけてね）',
    correctAnswer: 69,
    options: [56, 63, 69, 72],
    hint: 'まず 3 × 3 = 9、つぎに 20 × 3 = 60 だから…？',
  },
  {
    id: 'm6',
    num1: 45,
    num2: 2,
    operator: '×',
    questionText: '45 × 2 はいくつかな？（繰り上がりに気をつけてね！）',
    correctAnswer: 90,
    options: [80, 85, 90, 95],
    hint: '5 × 2 = 10 で、1が繰り上がるよ。4 × 2 = 8に 1をたすと…？',
  },
  {
    id: 'm7',
    num1: 12,
    num2: 4,
    operator: '×',
    questionText: '12 × 4 はいくつかな？',
    correctAnswer: 48,
    options: [36, 44, 48, 52],
    hint: '2 × 4 = 8 と 10 × 4 = 40 をあわせよう。',
  },

  // あまりのあるわり算 (Division with remainder)
  {
    id: 'm8',
    num1: 17,
    num2: 3,
    operator: '÷',
    questionText: '17 ÷ 3 の「商（しょう＝答えの数）」はいくつかな？',
    correctAnswer: 5,
    options: [4, 5, 6, 7],
    hint: '3のだんで17をこえない一番大きい数をさがそう。3 × 5 = 15、3 × 6 = 18。',
  },

  // 大きな数 (Large numbers)
  {
    id: 'm9',
    num1: 8000,
    num2: 2000,
    operator: '+',
    questionText: '8000 ＋ 2000 はいくつかな？',
    correctAnswer: 10000,
    options: [9000, 10000, 11000, 12000],
    hint: '「8000」に「2000」をたすと、1万（一万）になるよ。ゼロの数に気をつけよう！',
  },

  // 小数・分数 (Decimals & Fractions)
  {
    id: 'm10',
    num1: 3, // representing 0.3 + 0.4
    num2: 4,
    operator: '+',
    questionText: '0.3 ＋ 0.4 はいくつかな？',
    correctAnswer: 7, // will map to 0.7
    options: [1, 5, 7, 9], // maps to 0.1, 0.5, 0.7, 0.9 in UI
    hint: '0.1が、3個と4個あるから、あわせて何個かな？',
  },

  // 追加問題：基礎反復ドリル（計算・文章題・単位）
  {
    id: 'm_add_basic_001',
    num1: 8,
    num2: 7,
    operator: '+',
    questionText: '8 ＋ 7 はいくつかな？',
    correctAnswer: 15,
    options: [15, 17, 16, 14],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_002',
    num1: 9,
    num2: 6,
    operator: '+',
    questionText: '9 ＋ 6 はいくつかな？',
    correctAnswer: 15,
    options: [17, 14, 15, 16],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_003',
    num1: 14,
    num2: 8,
    operator: '+',
    questionText: '14 ＋ 8 はいくつかな？',
    correctAnswer: 22,
    options: [21, 24, 23, 22],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_004',
    num1: 26,
    num2: 7,
    operator: '+',
    questionText: '26 ＋ 7 はいくつかな？',
    correctAnswer: 33,
    options: [35, 34, 32, 33],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_005',
    num1: 38,
    num2: 5,
    operator: '+',
    questionText: '38 ＋ 5 はいくつかな？',
    correctAnswer: 43,
    options: [44, 42, 43, 45],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_006',
    num1: 47,
    num2: 6,
    operator: '+',
    questionText: '47 ＋ 6 はいくつかな？',
    correctAnswer: 53,
    options: [54, 55, 52, 53],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_007',
    num1: 58,
    num2: 9,
    operator: '+',
    questionText: '58 ＋ 9 はいくつかな？',
    correctAnswer: 67,
    options: [67, 69, 68, 66],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_008',
    num1: 69,
    num2: 8,
    operator: '+',
    questionText: '69 ＋ 8 はいくつかな？',
    correctAnswer: 77,
    options: [79, 76, 78, 77],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_009',
    num1: 125,
    num2: 34,
    operator: '+',
    questionText: '125 ＋ 34 はいくつかな？',
    correctAnswer: 159,
    options: [161, 158, 160, 159],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_010',
    num1: 236,
    num2: 41,
    operator: '+',
    questionText: '236 ＋ 41 はいくつかな？',
    correctAnswer: 277,
    options: [277, 279, 278, 276],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_011',
    num1: 148,
    num2: 27,
    operator: '+',
    questionText: '148 ＋ 27 はいくつかな？',
    correctAnswer: 175,
    options: [175, 176, 177, 174],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_012',
    num1: 356,
    num2: 28,
    operator: '+',
    questionText: '356 ＋ 28 はいくつかな？',
    correctAnswer: 384,
    options: [383, 385, 386, 384],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_013',
    num1: 472,
    num2: 39,
    operator: '+',
    questionText: '472 ＋ 39 はいくつかな？',
    correctAnswer: 511,
    options: [511, 510, 512, 513],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_014',
    num1: 589,
    num2: 16,
    operator: '+',
    questionText: '589 ＋ 16 はいくつかな？',
    correctAnswer: 605,
    options: [605, 607, 604, 606],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_015',
    num1: 604,
    num2: 27,
    operator: '+',
    questionText: '604 ＋ 27 はいくつかな？',
    correctAnswer: 631,
    options: [633, 631, 630, 632],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_016',
    num1: 735,
    num2: 48,
    operator: '+',
    questionText: '735 ＋ 48 はいくつかな？',
    correctAnswer: 783,
    options: [784, 785, 782, 783],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_017',
    num1: 128,
    num2: 236,
    operator: '+',
    questionText: '128 ＋ 236 はいくつかな？',
    correctAnswer: 364,
    options: [363, 366, 364, 365],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_018',
    num1: 347,
    num2: 258,
    operator: '+',
    questionText: '347 ＋ 258 はいくつかな？',
    correctAnswer: 605,
    options: [607, 604, 605, 606],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_019',
    num1: 409,
    num2: 186,
    operator: '+',
    questionText: '409 ＋ 186 はいくつかな？',
    correctAnswer: 595,
    options: [597, 594, 596, 595],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_add_basic_020',
    num1: 568,
    num2: 237,
    operator: '+',
    questionText: '568 ＋ 237 はいくつかな？',
    correctAnswer: 805,
    options: [807, 805, 806, 804],
    hint: '一の位から順番にたして、10をこえたら十の位へくり上げよう。',
  },
  {
    id: 'm_sub_basic_001',
    num1: 15,
    num2: 8,
    operator: '-',
    questionText: '15 － 8 はいくつかな？',
    correctAnswer: 7,
    options: [8, 6, 9, 7],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_002',
    num1: 23,
    num2: 7,
    operator: '-',
    questionText: '23 － 7 はいくつかな？',
    correctAnswer: 16,
    options: [17, 16, 15, 18],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_003',
    num1: 42,
    num2: 9,
    operator: '-',
    questionText: '42 － 9 はいくつかな？',
    correctAnswer: 33,
    options: [35, 33, 34, 32],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_004',
    num1: 51,
    num2: 6,
    operator: '-',
    questionText: '51 － 6 はいくつかな？',
    correctAnswer: 45,
    options: [46, 44, 47, 45],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_005',
    num1: 64,
    num2: 8,
    operator: '-',
    questionText: '64 － 8 はいくつかな？',
    correctAnswer: 56,
    options: [58, 56, 57, 55],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_006',
    num1: 70,
    num2: 5,
    operator: '-',
    questionText: '70 － 5 はいくつかな？',
    correctAnswer: 65,
    options: [67, 65, 66, 64],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_007',
    num1: 83,
    num2: 27,
    operator: '-',
    questionText: '83 － 27 はいくつかな？',
    correctAnswer: 56,
    options: [56, 57, 55, 58],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_008',
    num1: 94,
    num2: 38,
    operator: '-',
    questionText: '94 － 38 はいくつかな？',
    correctAnswer: 56,
    options: [56, 57, 58, 55],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_009',
    num1: 120,
    num2: 45,
    operator: '-',
    questionText: '120 － 45 はいくつかな？',
    correctAnswer: 75,
    options: [76, 75, 77, 74],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_010',
    num1: 203,
    num2: 18,
    operator: '-',
    questionText: '203 － 18 はいくつかな？',
    correctAnswer: 185,
    options: [185, 184, 186, 187],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_011',
    num1: 300,
    num2: 75,
    operator: '-',
    questionText: '300 － 75 はいくつかな？',
    correctAnswer: 225,
    options: [227, 225, 226, 224],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_012',
    num1: 456,
    num2: 129,
    operator: '-',
    questionText: '456 － 129 はいくつかな？',
    correctAnswer: 327,
    options: [328, 326, 329, 327],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_013',
    num1: 602,
    num2: 247,
    operator: '-',
    questionText: '602 － 247 はいくつかな？',
    correctAnswer: 355,
    options: [357, 355, 354, 356],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_014',
    num1: 740,
    num2: 368,
    operator: '-',
    questionText: '740 － 368 はいくつかな？',
    correctAnswer: 372,
    options: [372, 374, 371, 373],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_015',
    num1: 900,
    num2: 451,
    operator: '-',
    questionText: '900 － 451 はいくつかな？',
    correctAnswer: 449,
    options: [449, 450, 448, 451],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_sub_basic_016',
    num1: 1000,
    num2: 375,
    operator: '-',
    questionText: '1000 － 375 はいくつかな？',
    correctAnswer: 625,
    options: [625, 627, 624, 626],
    hint: '一の位から順番にひいて、ひけないときは上の位から10を借りよう。',
  },
  {
    id: 'm_mul_table_001',
    num1: 2,
    num2: 2,
    operator: '×',
    questionText: '2 × 2 はいくつかな？（九九を使おう）',
    correctAnswer: 4,
    options: [3, 5, 4, 6],
    hint: '2のだん、または2のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_002',
    num1: 2,
    num2: 3,
    operator: '×',
    questionText: '2 × 3 はいくつかな？（九九を使おう）',
    correctAnswer: 6,
    options: [6, 5, 7, 8],
    hint: '2のだん、または3のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_003',
    num1: 2,
    num2: 4,
    operator: '×',
    questionText: '2 × 4 はいくつかな？（九九を使おう）',
    correctAnswer: 8,
    options: [8, 9, 10, 7],
    hint: '2のだん、または4のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_004',
    num1: 2,
    num2: 5,
    operator: '×',
    questionText: '2 × 5 はいくつかな？（九九を使おう）',
    correctAnswer: 10,
    options: [9, 11, 12, 10],
    hint: '2のだん、または5のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_005',
    num1: 2,
    num2: 6,
    operator: '×',
    questionText: '2 × 6 はいくつかな？（九九を使おう）',
    correctAnswer: 12,
    options: [11, 13, 12, 14],
    hint: '2のだん、または6のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_006',
    num1: 2,
    num2: 7,
    operator: '×',
    questionText: '2 × 7 はいくつかな？（九九を使おう）',
    correctAnswer: 14,
    options: [15, 14, 16, 13],
    hint: '2のだん、または7のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_007',
    num1: 2,
    num2: 8,
    operator: '×',
    questionText: '2 × 8 はいくつかな？（九九を使おう）',
    correctAnswer: 16,
    options: [15, 18, 16, 17],
    hint: '2のだん、または8のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_008',
    num1: 2,
    num2: 9,
    operator: '×',
    questionText: '2 × 9 はいくつかな？（九九を使おう）',
    correctAnswer: 18,
    options: [19, 20, 17, 18],
    hint: '2のだん、または9のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_009',
    num1: 3,
    num2: 2,
    operator: '×',
    questionText: '3 × 2 はいくつかな？（九九を使おう）',
    correctAnswer: 6,
    options: [8, 6, 7, 5],
    hint: '3のだん、または2のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_010',
    num1: 3,
    num2: 3,
    operator: '×',
    questionText: '3 × 3 はいくつかな？（九九を使おう）',
    correctAnswer: 9,
    options: [10, 9, 11, 8],
    hint: '3のだん、または3のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_011',
    num1: 3,
    num2: 4,
    operator: '×',
    questionText: '3 × 4 はいくつかな？（九九を使おう）',
    correctAnswer: 12,
    options: [11, 12, 14, 13],
    hint: '3のだん、または4のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_012',
    num1: 3,
    num2: 5,
    operator: '×',
    questionText: '3 × 5 はいくつかな？（九九を使おう）',
    correctAnswer: 15,
    options: [15, 16, 14, 17],
    hint: '3のだん、または5のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_013',
    num1: 3,
    num2: 6,
    operator: '×',
    questionText: '3 × 6 はいくつかな？（九九を使おう）',
    correctAnswer: 18,
    options: [17, 18, 19, 20],
    hint: '3のだん、または6のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_014',
    num1: 3,
    num2: 7,
    operator: '×',
    questionText: '3 × 7 はいくつかな？（九九を使おう）',
    correctAnswer: 21,
    options: [20, 22, 21, 23],
    hint: '3のだん、または7のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_015',
    num1: 3,
    num2: 8,
    operator: '×',
    questionText: '3 × 8 はいくつかな？（九九を使おう）',
    correctAnswer: 24,
    options: [23, 26, 25, 24],
    hint: '3のだん、または8のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_016',
    num1: 3,
    num2: 9,
    operator: '×',
    questionText: '3 × 9 はいくつかな？（九九を使おう）',
    correctAnswer: 27,
    options: [27, 28, 29, 26],
    hint: '3のだん、または9のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_017',
    num1: 4,
    num2: 2,
    operator: '×',
    questionText: '4 × 2 はいくつかな？（九九を使おう）',
    correctAnswer: 8,
    options: [10, 8, 7, 9],
    hint: '4のだん、または2のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_018',
    num1: 4,
    num2: 3,
    operator: '×',
    questionText: '4 × 3 はいくつかな？（九九を使おう）',
    correctAnswer: 12,
    options: [13, 14, 12, 11],
    hint: '4のだん、または3のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_019',
    num1: 4,
    num2: 4,
    operator: '×',
    questionText: '4 × 4 はいくつかな？（九九を使おう）',
    correctAnswer: 16,
    options: [17, 18, 15, 16],
    hint: '4のだん、または4のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_020',
    num1: 4,
    num2: 5,
    operator: '×',
    questionText: '4 × 5 はいくつかな？（九九を使おう）',
    correctAnswer: 20,
    options: [21, 22, 20, 19],
    hint: '4のだん、または5のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_021',
    num1: 4,
    num2: 6,
    operator: '×',
    questionText: '4 × 6 はいくつかな？（九九を使おう）',
    correctAnswer: 24,
    options: [26, 25, 23, 24],
    hint: '4のだん、または6のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_022',
    num1: 4,
    num2: 7,
    operator: '×',
    questionText: '4 × 7 はいくつかな？（九九を使おう）',
    correctAnswer: 28,
    options: [27, 30, 29, 28],
    hint: '4のだん、または7のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_023',
    num1: 4,
    num2: 8,
    operator: '×',
    questionText: '4 × 8 はいくつかな？（九九を使おう）',
    correctAnswer: 32,
    options: [32, 33, 31, 34],
    hint: '4のだん、または8のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_024',
    num1: 4,
    num2: 9,
    operator: '×',
    questionText: '4 × 9 はいくつかな？（九九を使おう）',
    correctAnswer: 36,
    options: [36, 37, 35, 38],
    hint: '4のだん、または9のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_025',
    num1: 5,
    num2: 2,
    operator: '×',
    questionText: '5 × 2 はいくつかな？（九九を使おう）',
    correctAnswer: 10,
    options: [9, 11, 10, 12],
    hint: '5のだん、または2のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_026',
    num1: 5,
    num2: 3,
    operator: '×',
    questionText: '5 × 3 はいくつかな？（九九を使おう）',
    correctAnswer: 15,
    options: [14, 16, 17, 15],
    hint: '5のだん、または3のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_027',
    num1: 5,
    num2: 4,
    operator: '×',
    questionText: '5 × 4 はいくつかな？（九九を使おう）',
    correctAnswer: 20,
    options: [21, 22, 19, 20],
    hint: '5のだん、または4のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_028',
    num1: 5,
    num2: 5,
    operator: '×',
    questionText: '5 × 5 はいくつかな？（九九を使おう）',
    correctAnswer: 25,
    options: [27, 24, 25, 26],
    hint: '5のだん、または5のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_029',
    num1: 5,
    num2: 6,
    operator: '×',
    questionText: '5 × 6 はいくつかな？（九九を使おう）',
    correctAnswer: 30,
    options: [30, 29, 31, 32],
    hint: '5のだん、または6のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_030',
    num1: 5,
    num2: 7,
    operator: '×',
    questionText: '5 × 7 はいくつかな？（九九を使おう）',
    correctAnswer: 35,
    options: [37, 34, 36, 35],
    hint: '5のだん、または7のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_031',
    num1: 5,
    num2: 8,
    operator: '×',
    questionText: '5 × 8 はいくつかな？（九九を使おう）',
    correctAnswer: 40,
    options: [41, 40, 39, 42],
    hint: '5のだん、または8のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_032',
    num1: 5,
    num2: 9,
    operator: '×',
    questionText: '5 × 9 はいくつかな？（九九を使おう）',
    correctAnswer: 45,
    options: [44, 45, 47, 46],
    hint: '5のだん、または9のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_033',
    num1: 6,
    num2: 2,
    operator: '×',
    questionText: '6 × 2 はいくつかな？（九九を使おう）',
    correctAnswer: 12,
    options: [13, 11, 14, 12],
    hint: '6のだん、または2のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_034',
    num1: 6,
    num2: 3,
    operator: '×',
    questionText: '6 × 3 はいくつかな？（九九を使おう）',
    correctAnswer: 18,
    options: [18, 17, 20, 19],
    hint: '6のだん、または3のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_035',
    num1: 6,
    num2: 4,
    operator: '×',
    questionText: '6 × 4 はいくつかな？（九九を使おう）',
    correctAnswer: 24,
    options: [26, 23, 24, 25],
    hint: '6のだん、または4のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_table_036',
    num1: 6,
    num2: 5,
    operator: '×',
    questionText: '6 × 5 はいくつかな？（九九を使おう）',
    correctAnswer: 30,
    options: [30, 31, 32, 29],
    hint: '6のだん、または5のだんの九九を思い出そう。',
  },
  {
    id: 'm_mul_column_001',
    num1: 13,
    num2: 2,
    operator: '×',
    questionText: '13 × 2 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 26,
    options: [26, 25, 28, 27],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_002',
    num1: 14,
    num2: 3,
    operator: '×',
    questionText: '14 × 3 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 42,
    options: [44, 43, 42, 41],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_003',
    num1: 21,
    num2: 4,
    operator: '×',
    questionText: '21 × 4 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 84,
    options: [86, 84, 83, 85],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_004',
    num1: 32,
    num2: 3,
    operator: '×',
    questionText: '32 × 3 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 96,
    options: [96, 97, 98, 95],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_005',
    num1: 43,
    num2: 2,
    operator: '×',
    questionText: '43 × 2 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 86,
    options: [85, 87, 88, 86],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_006',
    num1: 52,
    num2: 4,
    operator: '×',
    questionText: '52 × 4 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 208,
    options: [210, 209, 207, 208],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_007',
    num1: 61,
    num2: 5,
    operator: '×',
    questionText: '61 × 5 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 305,
    options: [306, 304, 307, 305],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_008',
    num1: 72,
    num2: 3,
    operator: '×',
    questionText: '72 × 3 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 216,
    options: [217, 216, 218, 215],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_009',
    num1: 84,
    num2: 2,
    operator: '×',
    questionText: '84 × 2 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 168,
    options: [168, 169, 170, 167],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_010',
    num1: 95,
    num2: 4,
    operator: '×',
    questionText: '95 × 4 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 380,
    options: [380, 382, 381, 379],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_011',
    num1: 126,
    num2: 3,
    operator: '×',
    questionText: '126 × 3 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 378,
    options: [378, 377, 379, 380],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_012',
    num1: 204,
    num2: 4,
    operator: '×',
    questionText: '204 × 4 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 816,
    options: [818, 817, 816, 815],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_013',
    num1: 315,
    num2: 2,
    operator: '×',
    questionText: '315 × 2 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 630,
    options: [631, 629, 632, 630],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_014',
    num1: 408,
    num2: 3,
    operator: '×',
    questionText: '408 × 3 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 1224,
    options: [1226, 1224, 1225, 1223],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_015',
    num1: 520,
    num2: 4,
    operator: '×',
    questionText: '520 × 4 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 2080,
    options: [2079, 2082, 2080, 2081],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_mul_column_016',
    num1: 607,
    num2: 5,
    operator: '×',
    questionText: '607 × 5 はいくつかな？（筆算で一の位からかけよう）',
    correctAnswer: 3035,
    options: [3036, 3035, 3037, 3034],
    hint: '一の位、十の位、百の位の順にかけて、くり上がりを忘れないようにしよう。',
  },
  {
    id: 'm_div_exact_001',
    num1: 4,
    num2: 2,
    operator: '÷',
    questionText: '4 ÷ 2 はいくつかな？',
    correctAnswer: 2,
    options: [1, 4, 3, 2],
    hint: '2 × □ = 4 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_002',
    num1: 6,
    num2: 2,
    operator: '÷',
    questionText: '6 ÷ 2 はいくつかな？',
    correctAnswer: 3,
    options: [3, 5, 2, 4],
    hint: '2 × □ = 6 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_003',
    num1: 8,
    num2: 2,
    operator: '÷',
    questionText: '8 ÷ 2 はいくつかな？',
    correctAnswer: 4,
    options: [4, 5, 6, 3],
    hint: '2 × □ = 8 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_004',
    num1: 10,
    num2: 2,
    operator: '÷',
    questionText: '10 ÷ 2 はいくつかな？',
    correctAnswer: 5,
    options: [6, 4, 7, 5],
    hint: '2 × □ = 10 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_005',
    num1: 12,
    num2: 2,
    operator: '÷',
    questionText: '12 ÷ 2 はいくつかな？',
    correctAnswer: 6,
    options: [6, 7, 8, 5],
    hint: '2 × □ = 12 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_006',
    num1: 14,
    num2: 2,
    operator: '÷',
    questionText: '14 ÷ 2 はいくつかな？',
    correctAnswer: 7,
    options: [6, 8, 7, 9],
    hint: '2 × □ = 14 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_007',
    num1: 16,
    num2: 2,
    operator: '÷',
    questionText: '16 ÷ 2 はいくつかな？',
    correctAnswer: 8,
    options: [8, 7, 9, 10],
    hint: '2 × □ = 16 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_008',
    num1: 18,
    num2: 2,
    operator: '÷',
    questionText: '18 ÷ 2 はいくつかな？',
    correctAnswer: 9,
    options: [10, 11, 8, 9],
    hint: '2 × □ = 18 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_009',
    num1: 6,
    num2: 3,
    operator: '÷',
    questionText: '6 ÷ 3 はいくつかな？',
    correctAnswer: 2,
    options: [1, 2, 3, 4],
    hint: '3 × □ = 6 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_010',
    num1: 9,
    num2: 3,
    operator: '÷',
    questionText: '9 ÷ 3 はいくつかな？',
    correctAnswer: 3,
    options: [5, 2, 4, 3],
    hint: '3 × □ = 9 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_011',
    num1: 12,
    num2: 3,
    operator: '÷',
    questionText: '12 ÷ 3 はいくつかな？',
    correctAnswer: 4,
    options: [5, 6, 4, 3],
    hint: '3 × □ = 12 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_012',
    num1: 15,
    num2: 3,
    operator: '÷',
    questionText: '15 ÷ 3 はいくつかな？',
    correctAnswer: 5,
    options: [5, 6, 7, 4],
    hint: '3 × □ = 15 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_013',
    num1: 18,
    num2: 3,
    operator: '÷',
    questionText: '18 ÷ 3 はいくつかな？',
    correctAnswer: 6,
    options: [6, 8, 7, 5],
    hint: '3 × □ = 18 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_014',
    num1: 21,
    num2: 3,
    operator: '÷',
    questionText: '21 ÷ 3 はいくつかな？',
    correctAnswer: 7,
    options: [7, 6, 9, 8],
    hint: '3 × □ = 21 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_015',
    num1: 24,
    num2: 3,
    operator: '÷',
    questionText: '24 ÷ 3 はいくつかな？',
    correctAnswer: 8,
    options: [9, 7, 10, 8],
    hint: '3 × □ = 24 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_016',
    num1: 27,
    num2: 3,
    operator: '÷',
    questionText: '27 ÷ 3 はいくつかな？',
    correctAnswer: 9,
    options: [10, 11, 8, 9],
    hint: '3 × □ = 27 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_017',
    num1: 8,
    num2: 4,
    operator: '÷',
    questionText: '8 ÷ 4 はいくつかな？',
    correctAnswer: 2,
    options: [3, 2, 4, 1],
    hint: '4 × □ = 8 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_018',
    num1: 12,
    num2: 4,
    operator: '÷',
    questionText: '12 ÷ 4 はいくつかな？',
    correctAnswer: 3,
    options: [4, 3, 5, 2],
    hint: '4 × □ = 12 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_019',
    num1: 16,
    num2: 4,
    operator: '÷',
    questionText: '16 ÷ 4 はいくつかな？',
    correctAnswer: 4,
    options: [4, 3, 6, 5],
    hint: '4 × □ = 16 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_020',
    num1: 20,
    num2: 4,
    operator: '÷',
    questionText: '20 ÷ 4 はいくつかな？',
    correctAnswer: 5,
    options: [4, 7, 5, 6],
    hint: '4 × □ = 20 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_021',
    num1: 24,
    num2: 4,
    operator: '÷',
    questionText: '24 ÷ 4 はいくつかな？',
    correctAnswer: 6,
    options: [8, 7, 6, 5],
    hint: '4 × □ = 24 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_022',
    num1: 28,
    num2: 4,
    operator: '÷',
    questionText: '28 ÷ 4 はいくつかな？',
    correctAnswer: 7,
    options: [6, 8, 7, 9],
    hint: '4 × □ = 28 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_023',
    num1: 32,
    num2: 4,
    operator: '÷',
    questionText: '32 ÷ 4 はいくつかな？',
    correctAnswer: 8,
    options: [10, 9, 8, 7],
    hint: '4 × □ = 32 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_024',
    num1: 36,
    num2: 4,
    operator: '÷',
    questionText: '36 ÷ 4 はいくつかな？',
    correctAnswer: 9,
    options: [10, 8, 9, 11],
    hint: '4 × □ = 36 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_025',
    num1: 10,
    num2: 5,
    operator: '÷',
    questionText: '10 ÷ 5 はいくつかな？',
    correctAnswer: 2,
    options: [3, 1, 4, 2],
    hint: '5 × □ = 10 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_026',
    num1: 15,
    num2: 5,
    operator: '÷',
    questionText: '15 ÷ 5 はいくつかな？',
    correctAnswer: 3,
    options: [2, 5, 4, 3],
    hint: '5 × □ = 15 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_027',
    num1: 20,
    num2: 5,
    operator: '÷',
    questionText: '20 ÷ 5 はいくつかな？',
    correctAnswer: 4,
    options: [5, 4, 6, 3],
    hint: '5 × □ = 20 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_exact_028',
    num1: 25,
    num2: 5,
    operator: '÷',
    questionText: '25 ÷ 5 はいくつかな？',
    correctAnswer: 5,
    options: [6, 4, 7, 5],
    hint: '5 × □ = 25 になる数を、九九からさがそう。',
  },
  {
    id: 'm_div_rem_q_001',
    num1: 17,
    num2: 5,
    operator: '÷',
    questionText: '17 ÷ 5 の商（しょう）はいくつかな？',
    correctAnswer: 3,
    options: [3, 4, 2, 5],
    hint: '5のだんで、17をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_001',
    num1: 17,
    num2: 5,
    operator: '÷',
    questionText: '17 ÷ 5 のあまりはいくつかな？',
    correctAnswer: 2,
    options: [3, 1, 2, 4],
    hint: '5 × 3 = 15。17から15をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_002',
    num1: 22,
    num2: 4,
    operator: '÷',
    questionText: '22 ÷ 4 の商（しょう）はいくつかな？',
    correctAnswer: 5,
    options: [6, 7, 4, 5],
    hint: '4のだんで、22をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_002',
    num1: 22,
    num2: 4,
    operator: '÷',
    questionText: '22 ÷ 4 のあまりはいくつかな？',
    correctAnswer: 2,
    options: [1, 3, 2, 4],
    hint: '4 × 5 = 20。22から20をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_003',
    num1: 29,
    num2: 6,
    operator: '÷',
    questionText: '29 ÷ 6 の商（しょう）はいくつかな？',
    correctAnswer: 4,
    options: [3, 5, 6, 4],
    hint: '6のだんで、29をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_003',
    num1: 29,
    num2: 6,
    operator: '÷',
    questionText: '29 ÷ 6 のあまりはいくつかな？',
    correctAnswer: 5,
    options: [7, 5, 6, 4],
    hint: '6 × 4 = 24。29から24をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_004',
    num1: 34,
    num2: 7,
    operator: '÷',
    questionText: '34 ÷ 7 の商（しょう）はいくつかな？',
    correctAnswer: 4,
    options: [6, 5, 4, 3],
    hint: '7のだんで、34をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_004',
    num1: 34,
    num2: 7,
    operator: '÷',
    questionText: '34 ÷ 7 のあまりはいくつかな？',
    correctAnswer: 6,
    options: [5, 8, 6, 7],
    hint: '7 × 4 = 28。34から28をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_005',
    num1: 41,
    num2: 8,
    operator: '÷',
    questionText: '41 ÷ 8 の商（しょう）はいくつかな？',
    correctAnswer: 5,
    options: [4, 6, 5, 7],
    hint: '8のだんで、41をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_005',
    num1: 41,
    num2: 8,
    operator: '÷',
    questionText: '41 ÷ 8 のあまりはいくつかな？',
    correctAnswer: 1,
    options: [1, 2, 3, 0],
    hint: '8 × 5 = 40。41から40をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_006',
    num1: 46,
    num2: 9,
    operator: '÷',
    questionText: '46 ÷ 9 の商（しょう）はいくつかな？',
    correctAnswer: 5,
    options: [6, 5, 7, 4],
    hint: '9のだんで、46をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_006',
    num1: 46,
    num2: 9,
    operator: '÷',
    questionText: '46 ÷ 9 のあまりはいくつかな？',
    correctAnswer: 1,
    options: [1, 3, 0, 2],
    hint: '9 × 5 = 45。46から45をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_007',
    num1: 19,
    num2: 3,
    operator: '÷',
    questionText: '19 ÷ 3 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [7, 5, 8, 6],
    hint: '3のだんで、19をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_007',
    num1: 19,
    num2: 3,
    operator: '÷',
    questionText: '19 ÷ 3 のあまりはいくつかな？',
    correctAnswer: 1,
    options: [3, 0, 1, 2],
    hint: '3 × 6 = 18。19から18をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_008',
    num1: 25,
    num2: 4,
    operator: '÷',
    questionText: '25 ÷ 4 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [8, 5, 6, 7],
    hint: '4のだんで、25をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_008',
    num1: 25,
    num2: 4,
    operator: '÷',
    questionText: '25 ÷ 4 のあまりはいくつかな？',
    correctAnswer: 1,
    options: [2, 3, 1, 0],
    hint: '4 × 6 = 24。25から24をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_009',
    num1: 31,
    num2: 5,
    operator: '÷',
    questionText: '31 ÷ 5 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [6, 8, 7, 5],
    hint: '5のだんで、31をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_009',
    num1: 31,
    num2: 5,
    operator: '÷',
    questionText: '31 ÷ 5 のあまりはいくつかな？',
    correctAnswer: 1,
    options: [1, 3, 0, 2],
    hint: '5 × 6 = 30。31から30をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_010',
    num1: 38,
    num2: 6,
    operator: '÷',
    questionText: '38 ÷ 6 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [5, 7, 8, 6],
    hint: '6のだんで、38をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_010',
    num1: 38,
    num2: 6,
    operator: '÷',
    questionText: '38 ÷ 6 のあまりはいくつかな？',
    correctAnswer: 2,
    options: [3, 4, 2, 1],
    hint: '6 × 6 = 36。38から36をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_011',
    num1: 44,
    num2: 7,
    operator: '÷',
    questionText: '44 ÷ 7 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [6, 5, 8, 7],
    hint: '7のだんで、44をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_011',
    num1: 44,
    num2: 7,
    operator: '÷',
    questionText: '44 ÷ 7 のあまりはいくつかな？',
    correctAnswer: 2,
    options: [3, 1, 2, 4],
    hint: '7 × 6 = 42。44から42をひいた数があまりだよ。',
  },
  {
    id: 'm_div_rem_q_012',
    num1: 53,
    num2: 8,
    operator: '÷',
    questionText: '53 ÷ 8 の商（しょう）はいくつかな？',
    correctAnswer: 6,
    options: [5, 7, 6, 8],
    hint: '8のだんで、53をこえない一番大きい数をさがそう。',
  },
  {
    id: 'm_div_rem_r_012',
    num1: 53,
    num2: 8,
    operator: '÷',
    questionText: '53 ÷ 8 のあまりはいくつかな？',
    correctAnswer: 5,
    options: [6, 5, 7, 4],
    hint: '8 × 6 = 48。53から48をひいた数があまりだよ。',
  },
  {
    id: 'm_place_001',
    num1: 3000,
    num2: 4000,
    operator: '+',
    questionText: '3000 ＋ 4000 はいくつかな？',
    correctAnswer: 7000,
    options: [7001, 7002, 6999, 7000],
    hint: '千のまとまりが3こ＋4こで7こだよ。',
  },
  {
    id: 'm_place_002',
    num1: 5000,
    num2: 2500,
    operator: '+',
    questionText: '5000 ＋ 2500 はいくつかな？',
    correctAnswer: 7500,
    options: [7499, 7500, 7502, 7501],
    hint: '千と百の位をそろえてたそう。',
  },
  {
    id: 'm_place_003',
    num1: 10000,
    num2: 3000,
    operator: '-',
    questionText: '10000 － 3000 はいくつかな？',
    correctAnswer: 7000,
    options: [7000, 7002, 6999, 7001],
    hint: '1万から3千をひくと、千のまとまりはいくつ残るかな。',
  },
  {
    id: 'm_place_004',
    num1: 8200,
    num2: 600,
    operator: '+',
    questionText: '8200 ＋ 600 はいくつかな？',
    correctAnswer: 8800,
    options: [8800, 8802, 8799, 8801],
    hint: '百の位に注目してたそう。',
  },
  {
    id: 'm_place_005',
    num1: 9000,
    num2: 4500,
    operator: '-',
    questionText: '9000 － 4500 はいくつかな？',
    correctAnswer: 4500,
    options: [4501, 4502, 4500, 4499],
    hint: '9000を90百、4500を45百と考えてもいいね。',
  },
  {
    id: 'm_place_006',
    num1: 12000,
    num2: 8000,
    operator: '-',
    questionText: '12000 － 8000 はいくつかな？',
    correctAnswer: 4000,
    options: [4001, 4002, 3999, 4000],
    hint: '千のまとまりで考えよう。',
  },
  {
    id: 'm_unit_001',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '1時間は何分かな？',
    correctAnswer: 60,
    options: [30, 50, 60, 100],
    hint: '時計の長いはりが1周すると60分だよ。',
  },
  {
    id: 'm_unit_002',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '2時間は何分かな？',
    correctAnswer: 120,
    options: [60, 90, 120, 200],
    hint: '1時間は60分。60分が2こで何分かな？',
  },
  {
    id: 'm_unit_003',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '90分は何時間何分かな？「何分」の部分だけ答えよう。',
    correctAnswer: 30,
    options: [0, 15, 30, 60],
    hint: '90分は60分と30分。60分は1時間だよ。',
  },
  {
    id: 'm_unit_004',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '100cm は何mかな？',
    correctAnswer: 1,
    options: [1, 10, 100, 1000],
    hint: '100cmで1mだよ。',
  },
  {
    id: 'm_unit_005',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '1m50cm は何cmかな？',
    correctAnswer: 150,
    options: [105, 150, 510, 100],
    hint: '1mは100cm。100cmに50cmをたそう。',
  },
  {
    id: 'm_unit_006',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '1L は何dLかな？',
    correctAnswer: 10,
    options: [1, 10, 100, 1000],
    hint: '1Lは10dLだよ。',
  },
  {
    id: 'm_unit_007',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '1000mL は何Lかな？',
    correctAnswer: 1,
    options: [1, 10, 100, 1000],
    hint: '1000mLで1Lだよ。',
  },
  {
    id: 'm_unit_008',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '100円玉3まいと10円玉4まいで何円かな？',
    correctAnswer: 340,
    options: [304, 330, 340, 430],
    hint: '100円が3まいで300円、10円が4まいで40円。',
  },
  {
    id: 'm_unit_009',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '500円から180円使いました。残りは何円かな？',
    correctAnswer: 320,
    options: [220, 300, 320, 380],
    hint: '500－100－80のように分けて考えよう。',
  },
  {
    id: 'm_unit_010',
    num1: 0,
    num2: 0,
    operator: '+',
    questionText: '45分後に15分たつと、あわせて何分かな？',
    correctAnswer: 60,
    options: [50, 55, 60, 70],
    hint: '45分に15分をたすと、時計の1時間分になるよ。',
  }
];

// 3rd Grade Kanji Questions
export const KANJI_QUESTIONS: KanjiQuestion[] = [
  {
    id: 'k1',
    kanji: '赤',
    reading: 'あか',
    contextBefore: 'ポストは ',
    contextAfter: ' い色をしています。',
    hint: '「土」の下に「八」のような形を書くよ。赤（あか）信号の「あか」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k2',
    kanji: '青',
    reading: 'あお',
    contextBefore: 'さわやかに晴れた ',
    contextAfter: ' 空がひろがっている。',
    hint: '上は「ま（キ）」、下は「月」だよ。青（あお）色の「あお」だね。',
    strokeCount: 8,
  },
  {
    id: 'k3',
    kanji: '歌',
    reading: 'うた',
    contextBefore: 'みんなで元気に ',
    contextAfter: ' をうたいましょう。',
    hint: '左側は「可」をたてに2つ並べて、右側は「欠」を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k4',
    kanji: '森',
    reading: 'もり',
    contextBefore: 'たくさんの木が生いしげる ',
    contextAfter: ' の中をさんぽする。',
    hint: '「木」という漢字を、上に1つ、下に2つ、合計3つ書んだ！',
    strokeCount: 12,
  },
  {
    id: 'k5',
    kanji: '駅',
    reading: 'えき',
    contextBefore: '電車に乗るために ',
    contextAfter: ' まで歩いていきました。',
    hint: '左側は「馬（うまへん）」、右側は「尺」を書くよ。電車の「えき」だね。',
    strokeCount: 14,
  },
  {
    id: 'k6',
    kanji: '花',
    reading: 'はな',
    contextBefore: '庭にきれいな ',
    contextAfter: ' がさきました。',
    hint: '上は「くさかんむり」、下は「化」という漢字を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k7',
    kanji: '寺',
    reading: 'てら',
    contextBefore: '古いお ',
    contextAfter: ' で鐘（かね）の音がひびく。',
    hint: '上は「土」、下は「寸」を書くよ。お「てら」の漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k8',
    kanji: '走',
    reading: 'はし',
    contextBefore: '校庭を全力で ',
    contextAfter: ' る練習をします。',
    hint: '「土」の下に、走る足の形（「止」に似た形）を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k9',
    kanji: '茶',
    reading: 'ちゃ',
    contextBefore: '温かい緑 ',
    contextAfter: ' を飲んでほっとする。',
    hint: '上は「くさかんむり」、中は「人」のような形、下は「ホ」だよ。',
    strokeCount: 9,
  },
  {
    id: 'k10',
    kanji: '重',
    reading: 'おも',
    contextBefore: 'このダンボールはとても ',
    contextAfter: ' いです。',
    hint: '「千」と「里」が組み合わさったような漢字だよ。たいじゅうの「じゅう」でもあるよ。',
    strokeCount: 9,
  },
  {
    id: 'k11',
    kanji: '葉',
    reading: 'は',
    contextBefore: '秋になると、木の',
    contextAfter: 'が赤や黄色になります。',
    hint: '上は「くさかんむり」、中は「世」、下は「木」を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k12',
    kanji: '起',
    reading: 'お',
    contextBefore: '朝は早く',
    contextAfter: 'きて、あさごはんを食べましょう。',
    hint: '左側は「走」、右側は「己（おのれ）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k13',
    kanji: '速',
    reading: 'はや',
    contextBefore: '新幹線はとても',
    contextAfter: 'い乗り物です。',
    hint: 'しんにょうの中に「束（たば）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k14',
    kanji: '面',
    reading: 'めん',
    contextBefore: 'テレビのおもしろい画',
    contextAfter: 'をながめる。',
    hint: '一番上は「一」で、その下には目のような形を囲んで書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k15',
    kanji: '向',
    reading: 'む',
    contextBefore: 'あちらの',
    contextAfter: 'こうに見えるのが富士山です。',
    hint: '「の」の下に「冂」と「口」を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k16',
    kanji: '緑',
    reading: 'みどり',
    contextBefore: '森にはたくさんの',
    contextAfter: 'があふれています。',
    hint: '左側は「糸（いとへん）」、右側は「彔」を書くよ。みどり色の漢字だよ。',
    strokeCount: 14,
  },
  {
    id: 'k17',
    kanji: '感',
    reading: 'かん',
    contextBefore: 'テストが終わって、ホッとした',
    contextAfter: 'じがする。',
    hint: '「咸」の下に「心」を組みあわせた漢字だよ。',
    strokeCount: 13,
  },
  {
    id: 'k18',
    kanji: '豆',
    reading: 'まめ',
    contextBefore: '節分の日には、お',
    contextAfter: 'まきをして鬼を退治します。',
    hint: '一番上は「一」、中は「口」、下は「ソ」に「一」を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k19',
    kanji: '物',
    reading: 'もの',
    contextBefore: 'スーパーへ買い',
    contextAfter: 'に行きます。',
    hint: '左側は「牛（うしへん）」、右側は「勿」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k20',
    kanji: '様',
    reading: 'さま',
    contextBefore: 'お殿',
    contextAfter: 'のような立派な服を着ています。',
    hint: '左側は「木（きへん）」、右側は「羊」の下に美の下半分のような形だよ。',
    strokeCount: 14,
  },
  {
    id: 'k21',
    kanji: '仕',
    reading: 'し',
    contextBefore: 'お父さんのお',
    contextAfter: 'ごとをおうえんする。',
    hint: '左側は「人（にんべん）」、右側は「士」を書くよ。仕事の「し」だよ。',
    strokeCount: 5,
  },
  {
    id: 'k22',
    kanji: '練',
    reading: 'れん',
    contextBefore: 'ピアノの習い事の',
    contextAfter: '習（しゅう）をがんばる。',
    hint: '左側は「糸（いとへん）」、右側は「東」を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k23',
    kanji: '習',
    reading: 'なら',
    contextBefore: '先生に漢字の正しい書き方を',
    contextAfter: 'う。',
    hint: '上は「羽」、下は「白」を組み合わせた漢字だよ。',
    strokeCount: 11,
  },
  {
    id: 'k24',
    kanji: '州',
    reading: 'しゅう',
    contextBefore: '私たちの住む本',
    contextAfter: 'は、日本で一番大きな島です。',
    hint: '「川」の中に点が3つ入るイメージで書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k25',
    kanji: '央',
    reading: 'おう',
    contextBefore: '校庭の中',
    contextAfter: 'にみんなで大きな丸をつくる。',
    hint: '「大」の上の部分に四角い囲みが入る形だよ。',
    strokeCount: 5,
  },
  {
    id: 'k26',
    kanji: '横',
    reading: 'よこ',
    contextBefore: '信号のない道路を',
    contextAfter: 'ぎるときは左右を確認しよう。',
    hint: '左側は「木」、右側は「黄（きいろ）」を書くよ。',
    strokeCount: 15,
  },
  {
    id: 'k27',
    kanji: '倍',
    reading: 'ばい',
    contextBefore: 'ゲームの得点が二',
    contextAfter: 'になって大よろこび！',
    hint: '左側は「人（にんべん）」、右側は「咅（立の下に口）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k28',
    kanji: '館',
    reading: 'かん',
    contextBefore: '学校の図書',
    contextAfter: 'で面白い絵本をかりる。',
    hint: '左側は「食（しょくへん）」、右側は「官」を書くよ。',
    strokeCount: 16,
  },
  {
    id: 'k29',
    kanji: '事',
    reading: 'こと',
    contextBefore: '今日あったでき',
    contextAfter: 'を日記に書き残す。',
    hint: '「一」の下に「口」を書き、縦に貫き、最後に「フ」のようなハネだよ。',
    strokeCount: 8,
  },
  {
    id: 'k30',
    kanji: '号',
    reading: 'ごう',
    contextBefore: '青信',
    contextAfter: 'になったら横断歩道をわたります。',
    hint: '「口」の下に「丂（ひらがなの「て」に似た形）」を書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k31',
    kanji: '使',
    reading: 'つか',
    contextBefore: 'お箸（はし）を上手に',
    contextAfter: 'ってごはんを食べましょう。',
    hint: '左側は「人（にんべん）」、右側は「吏」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k32',
    kanji: '意',
    reading: 'い',
    contextBefore: 'みんなの前で自分の',
    contextAfter: '見を発表します。',
    hint: '上に「音」、下に「心」を組み合わせた漢字だよ。',
    strokeCount: 13,
  },
  {
    id: 'k33',
    kanji: '味',
    reading: 'あじ',
    contextBefore: 'お母さんが作ったスープの',
    contextAfter: 'をみる。',
    hint: '左側は「口（くちへん）」、右側は「未」を書くよ。「末」と間違えないでね。',
    strokeCount: 8,
  },
  {
    id: 'k34',
    kanji: '漢',
    reading: 'かん',
    contextBefore: 'まいにちコツコツ',
    contextAfter: '字の練習をつづけよう。',
    hint: '左は「さんずい」、右は「廿（くさかんむり）」の下に「夫」を書くよ。',
    strokeCount: 13,
  },
  {
    id: 'k35',
    kanji: '表',
    reading: 'あらわ',
    contextBefore: '心の中の気持ちを絵に',
    contextAfter: 'してみよう。',
    hint: '「三」のような横線に「土」を組みあわせ、下は「衣」のようだよ。',
    strokeCount: 8,
  },
  {
    id: 'k36',
    kanji: '調',
    reading: 'しら',
    contextBefore: '辞書をひいて、わからない言葉を',
    contextAfter: 'べる。',
    hint: '左側は「言（ごんべん）」、右側は「周」を書くよ。',
    strokeCount: 15,
  },
  {
    id: 'k37',
    kanji: '柱',
    reading: 'はしら',
    contextBefore: 'このお寺には、とても太い',
    contextAfter: 'があります。',
    hint: '左側は「木」、右側は「主（ぬし）」を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k38',
    kanji: '所',
    reading: 'ところ',
    contextBefore: '秘密のば',
    contextAfter: 'に宝物をかくしておこう。',
    hint: '左側は「戸」、右側は「斤（おのづくり）」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k39',
    kanji: '持',
    reading: 'も',
    contextBefore: 'お気に入りのノートを手に',
    contextAfter: 'って出かける。',
    hint: '左側は「手（てへん）」、右側は「寺」を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k40',
    kanji: '局',
    reading: 'きょく',
    contextBefore: 'ハガキを出すために郵便',
    contextAfter: 'へ行きます。',
    hint: '「尸（しかばね）」の中に「句」が入る形だよ。',
    strokeCount: 7,
  },
  {
    id: 'k41',
    kanji: '配',
    reading: 'くば',
    contextBefore: '先生がみんなにプリントを',
    contextAfter: 'るのを手伝います。',
    hint: '左側は「酉」、右側は「己」を書くよ。配達（はいたつ）の「はい」だよ。',
    strokeCount: 10,
  },
  {
    id: 'k42',
    kanji: '住',
    reading: 'す',
    contextBefore: '緑豊かなすてきな町に',
    contextAfter: 'む。',
    hint: '左側は「人（にんべん）」、右側は「主」を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k43',
    kanji: '身',
    reading: 'み',
    contextBefore: '出かける前に、',
    contextAfter: 'じたくを整えましょう。',
    hint: '自分のからだを表す漢字だよ。中の右上に飛び出すハネに注意してね。',
    strokeCount: 7,
  },
  {
    id: 'k44',
    kanji: '育',
    reading: 'そだ',
    contextBefore: '朝顔の種をまいて、大切に',
    contextAfter: 'てる。',
    hint: '上は「充」の上半分のような形、下は「月」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k45',
    kanji: '守',
    reading: 'まも',
    contextBefore: '大切な約束はかならず',
    contextAfter: 'りましょう。',
    hint: '上は「うかんむり」、下は「寸」を書くよ。守る（まもる）の漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k46',
    kanji: '決',
    reading: 'き',
    contextBefore: '今日のおやつをどっちにするか',
    contextAfter: 'める。',
    hint: '左は「さんずい」、右は「夬」を書くよ。決定（けってい）の「けつ」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k47',
    kanji: '動',
    reading: 'うご',
    contextBefore: 'ゼンマイを巻くと、おもちゃが',
    contextAfter: 'きだします。',
    hint: '左側は「重」、右側は「力」を組み合わせた漢字だよ。',
    strokeCount: 11,
  },
  {
    id: 'k48',
    kanji: '問',
    reading: 'とい',
    contextBefore: '教科書にかかれている',
    contextAfter: 'に答えましょう。',
    hint: '「門（もんがまえ）」の中に「口」を書くよ。質問（しつもん）の「もん」だよ。',
    strokeCount: 11,
  },
  {
    id: 'k49',
    kanji: '題',
    reading: 'だい',
    contextBefore: '算数のむずかしい問',
    contextAfter: 'に挑戦してみる。',
    hint: '左は「是」、右は「頁（おおがい）」を組みあわせた漢字だよ。',
    strokeCount: 18,
  },
  {
    id: 'k50',
    kanji: '部',
    reading: 'ぶ',
    contextBefore: '自分の',
    contextAfter: '屋をお掃除してすっきりさせる。',
    hint: '左は「立」の下に「口」、右は「おおざと（阝）」を書くよ。',
    strokeCount: 11,
  },
  {
    id: 'k51',
    kanji: '筆',
    reading: 'ふで',
    contextBefore: '書道の時間には、',
    contextAfter: 'にすみをつけて文字を書きます。',
    hint: '上は「たけかんむり」、下は「聿（ふで）」を書くよ。鉛筆の「ひつ」だよ。',
    strokeCount: 12,
  },
  {
    id: 'k52',
    kanji: '者',
    reading: 'もの',
    contextBefore: 'このレースで一番速い',
    contextAfter: 'が優勝します。',
    hint: '「土」の下に「ノ」を斜めに引き、その下に「日」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k53',
    kanji: '都',
    reading: 'と',
    contextBefore: '日本の首',
    contextAfter: 'は、美しい東京です。',
    hint: '左は「者」、右は「おおざと（阝）」を書くよ。京都や首都の「と」だよ。',
    strokeCount: 11,
  },
  {
    id: 'k54',
    kanji: '氷',
    reading: 'こおり',
    contextBefore: 'ジュースに冷たい',
    contextAfter: 'を浮かべて飲む。',
    hint: '「水」の左上の部分に、ちょんと点（「丶」）を1つ付け足すよ。',
    strokeCount: 5,
  },
  {
    id: 'k55',
    kanji: '泳',
    reading: 'およ',
    contextBefore: '夏の体育の授業では、プールで',
    contextAfter: 'ぎます。',
    hint: '左側は「さんずい」、右側は「永」を書くよ。水泳の「えい」だよ。',
    strokeCount: 8,
  },
  {
    id: 'k56',
    kanji: '有',
    reading: 'ゆう',
    contextBefore: '世界的に',
    contextAfter: '名な絵画を美術館で見る。',
    hint: '「𠂇（ナの形）」の下に、「月」を組みあわせた漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k57',
    kanji: '返',
    reading: 'かえ',
    contextBefore: '図書館でかりた本を期日までに',
    contextAfter: 'す。',
    hint: 'しんにょうの中に「反」を書くよ。お返事の「へん」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k58',
    kanji: '遊',
    reading: 'あそ',
    contextBefore: '放課後は公園で友達と元気いっぱいに',
    contextAfter: 'ぶ。',
    hint: 'しんにょうの中に「汓」と「方」のような形を組み合わせた漢字だよ。',
    strokeCount: 12,
  },
  {
    id: 'k59',
    kanji: '開',
    reading: 'あ',
    contextBefore: '窓をいっぱいに',
    contextAfter: 'けて、新鮮な空気を取り入れよう。',
    hint: '「門（もんがまえ）」の中に「一」と「开（鳥居のような形）」を書くよ。',
    strokeCount: 12,
  },

  // 追加問題：国語の基礎漢字反復ドリル（1〜3年の基本漢字中心）
  {
    id: 'k_basic_001',
    kanji: '一',
    reading: 'いち',
    contextBefore: '数字の ',
    contextAfter: ' は、はじめの数です。',
    hint: '横にまっすぐ一本書くよ。',
    strokeCount: 1,
  },
  {
    id: 'k_basic_002',
    kanji: '二',
    reading: 'に',
    contextBefore: 'りんごが ',
    contextAfter: ' こあります。',
    hint: '横線を上から短く、下を長く書こう。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_003',
    kanji: '三',
    reading: 'さん',
    contextBefore: '朝・昼・夜の ',
    contextAfter: ' 回ごはんを食べます。',
    hint: '横線を三本、すき間をそろえて書こう。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_004',
    kanji: '四',
    reading: 'よん',
    contextBefore: '机の足は ',
    contextAfter: ' 本あります。',
    hint: '外の四角を書いてから中を書こう。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_005',
    kanji: '五',
    reading: 'ご',
    contextBefore: '片手の指は ',
    contextAfter: ' 本です。',
    hint: '横線とたて線の形に気をつけよう。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_006',
    kanji: '六',
    reading: 'ろく',
    contextBefore: 'さいころには ',
    contextAfter: ' までの目があります。',
    hint: '上に点、下に八のような形を書くよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_007',
    kanji: '七',
    reading: 'なな',
    contextBefore: '一週間は ',
    contextAfter: ' 日です。',
    hint: '横線からななめに下ろして、最後にはねよう。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_008',
    kanji: '八',
    reading: 'はち',
    contextBefore: 'たこには足が ',
    contextAfter: ' 本あります。',
    hint: '左右に開くように書こう。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_009',
    kanji: '九',
    reading: 'きゅう',
    contextBefore: '九九の最後は ',
    contextAfter: ' のだんです。',
    hint: '曲がってから最後にはねるよ。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_010',
    kanji: '十',
    reading: 'じゅう',
    contextBefore: '一の位が10こで ',
    contextAfter: ' になります。',
    hint: '横線を書いて、まん中にたて線を書こう。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_011',
    kanji: '日',
    reading: 'ひ',
    contextBefore: '朝になると ',
    contextAfter: ' がのぼります。',
    hint: '四角の中に横線を一本書くよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_012',
    kanji: '月',
    reading: 'つき',
    contextBefore: '夜空に ',
    contextAfter: ' が出ています。',
    hint: '外側を書いて、中に横線を二本入れるよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_013',
    kanji: '火',
    reading: 'ひ',
    contextBefore: 'キャンプで ',
    contextAfter: ' を使います。',
    hint: '人の形に点を二つ足すイメージだよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_014',
    kanji: '水',
    reading: 'みず',
    contextBefore: 'のどがかわいたので ',
    contextAfter: ' を飲みます。',
    hint: '真ん中の線から左右に広げよう。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_015',
    kanji: '木',
    reading: 'き',
    contextBefore: '公園に大きな ',
    contextAfter: ' が立っています。',
    hint: '十の下に左右のはらいを書こう。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_016',
    kanji: '金',
    reading: 'きん',
    contextBefore: '金曜日の ',
    contextAfter: ' はこの漢字です。',
    hint: '上は人の屋根、下は王に点を足した形だよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_017',
    kanji: '土',
    reading: 'つち',
    contextBefore: '花だんに ',
    contextAfter: ' を入れます。',
    hint: '横線を二本、たて線をまん中に書こう。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_018',
    kanji: '山',
    reading: 'やま',
    contextBefore: '遠くに高い ',
    contextAfter: ' が見えます。',
    hint: 'たて線三本の高さを変えて書こう。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_019',
    kanji: '川',
    reading: 'かわ',
    contextBefore: '大きな ',
    contextAfter: ' が流れています。',
    hint: '流れる水のように三本書くよ。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_020',
    kanji: '田',
    reading: 'た',
    contextBefore: '米を作る ',
    contextAfter: ' んぼがあります。',
    hint: '四角を書いて、中を十で区切るよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_021',
    kanji: '人',
    reading: 'ひと',
    contextBefore: 'やさしい ',
    contextAfter: ' になりたいです。',
    hint: '左はらいと右はらいをのびのび書こう。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_022',
    kanji: '口',
    reading: 'くち',
    contextBefore: '大きな ',
    contextAfter: ' をあけて歌います。',
    hint: '四角く、最後は下の線で閉じよう。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_023',
    kanji: '目',
    reading: 'め',
    contextBefore: '本を読むときは ',
    contextAfter: ' を大切にします。',
    hint: '日より中の横線が一本多いよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_024',
    kanji: '耳',
    reading: 'みみ',
    contextBefore: '音を聞くために ',
    contextAfter: ' を使います。',
    hint: '横線の数と長さに気をつけよう。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_025',
    kanji: '手',
    reading: 'て',
    contextBefore: 'えんぴつを ',
    contextAfter: ' に持ちます。',
    hint: '最後のたて線は下にはねよう。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_026',
    kanji: '足',
    reading: 'あし',
    contextBefore: '速く走るには ',
    contextAfter: ' を使います。',
    hint: '上は口、下は止に似た形だよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_027',
    kanji: '力',
    reading: 'ちから',
    contextBefore: '重い物を持つには ',
    contextAfter: ' がいります。',
    hint: '折れ曲がる線と、左はらいを書くよ。',
    strokeCount: 2,
  },
  {
    id: 'k_basic_028',
    kanji: '男',
    reading: 'おとこ',
    contextBefore: '弟は元気な ',
    contextAfter: ' の子です。',
    hint: '田の下に力を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_029',
    kanji: '女',
    reading: 'おんな',
    contextBefore: '姉はやさしい ',
    contextAfter: ' の子です。',
    hint: 'くの字と横線の交わりに気をつけよう。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_030',
    kanji: '子',
    reading: 'こ',
    contextBefore: '小さな ',
    contextAfter: ' どもが遊んでいます。',
    hint: '横線の上に丸みのある形を書くよ。',
    strokeCount: 3,
  },
  {
    id: 'k_basic_031',
    kanji: '学',
    reading: 'がく',
    contextBefore: '学校の ',
    contextAfter: ' はこの漢字です。',
    hint: '上はつかんむり、下は子を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_032',
    kanji: '校',
    reading: 'こう',
    contextBefore: '毎朝、 ',
    contextAfter: ' 門を通ります。',
    hint: '木へんに交わるの「交」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_033',
    kanji: '先',
    reading: 'せん',
    contextBefore: '先生の ',
    contextAfter: ' はこの漢字です。',
    hint: '上は牛に似た形、下は儿を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_034',
    kanji: '生',
    reading: 'せい',
    contextBefore: '生きるの ',
    contextAfter: ' はこの漢字です。',
    hint: '横線三本とたて線の長さに気をつけよう。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_035',
    kanji: '友',
    reading: 'とも',
    contextBefore: '休み時間に ',
    contextAfter: ' だちと遊びます。',
    hint: 'ナの形と又を組み合わせるよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_036',
    kanji: '名',
    reading: 'な',
    contextBefore: '自分の ',
    contextAfter: ' 前をていねいに書きます。',
    hint: '夕の下に口を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_037',
    kanji: '年',
    reading: 'とし',
    contextBefore: '一 ',
    contextAfter: ' は十二か月です。',
    hint: '横線の長さをそろえて、たて線を下ろそう。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_038',
    kanji: '時',
    reading: 'じ',
    contextBefore: '時計で ',
    contextAfter: ' こくを見ます。',
    hint: '日へんの右に寺を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_039',
    kanji: '分',
    reading: 'ふん',
    contextBefore: '10 ',
    contextAfter: ' 休けいします。',
    hint: '八の下に刀を書くよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_040',
    kanji: '今',
    reading: 'いま',
    contextBefore: ' ',
    contextAfter: ' から宿題を始めます。',
    hint: '人の屋根の下に点と折れ線を書くよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_041',
    kanji: '新',
    reading: 'あたら',
    contextBefore: ' ',
    contextAfter: ' しいノートを使います。',
    hint: '左は親に似た形、右は斤を書くよ。',
    strokeCount: 13,
  },
  {
    id: 'k_basic_042',
    kanji: '古',
    reading: 'ふる',
    contextBefore: ' ',
    contextAfter: ' い本を大切にします。',
    hint: '十の下に口を書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_043',
    kanji: '高',
    reading: 'たか',
    contextBefore: 'あのビルはとても ',
    contextAfter: ' いです。',
    hint: '上から順に、なべぶた・口・高い建物の形を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_044',
    kanji: '安',
    reading: 'やす',
    contextBefore: 'この店は値段が ',
    contextAfter: ' いです。',
    hint: 'うかんむりの下に女を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_045',
    kanji: '明',
    reading: 'あか',
    contextBefore: '朝になると外が ',
    contextAfter: ' るくなります。',
    hint: '日と月をならべて書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_046',
    kanji: '暗',
    reading: 'くら',
    contextBefore: '夜の道は ',
    contextAfter: ' いです。',
    hint: '日へんに音を書くよ。',
    strokeCount: 13,
  },
  {
    id: 'k_basic_047',
    kanji: '強',
    reading: 'つよ',
    contextBefore: '風がとても ',
    contextAfter: ' いです。',
    hint: '弓の右に虫を組み合わせるよ。',
    strokeCount: 11,
  },
  {
    id: 'k_basic_048',
    kanji: '弱',
    reading: 'よわ',
    contextBefore: '体が ',
    contextAfter: ' っているときは休みます。',
    hint: '弓が二つある形に点を入れるよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_049',
    kanji: '正',
    reading: 'ただ',
    contextBefore: '答えを ',
    contextAfter: ' しく直します。',
    hint: '一と止を組み合わせた形だよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_050',
    kanji: '早',
    reading: 'はや',
    contextBefore: '朝 ',
    contextAfter: ' く起きます。',
    hint: '日の下に十を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_051',
    kanji: '歩',
    reading: 'ある',
    contextBefore: '学校まで ',
    contextAfter: ' いて行きます。',
    hint: '止の下に少を組み合わせるよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_052',
    kanji: '止',
    reading: 'と',
    contextBefore: '赤信号で ',
    contextAfter: ' まります。',
    hint: 'たて線と横線の位置に気をつけよう。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_053',
    kanji: '帰',
    reading: 'かえ',
    contextBefore: '家に ',
    contextAfter: ' ります。',
    hint: '左側と右側のバランスを見て書こう。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_054',
    kanji: '来',
    reading: 'く',
    contextBefore: '友だちが家に ',
    contextAfter: ' る。',
    hint: '木の形に横線と点を足すよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_055',
    kanji: '行',
    reading: 'い',
    contextBefore: '公園へ ',
    contextAfter: ' きます。',
    hint: 'ぎょうにんべんの形を意識しよう。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_056',
    kanji: '聞',
    reading: 'き',
    contextBefore: '先生の話をよく ',
    contextAfter: ' きます。',
    hint: '門の中に耳を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k_basic_057',
    kanji: '読',
    reading: 'よ',
    contextBefore: '本を ',
    contextAfter: ' みます。',
    hint: '言べんの右に売を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k_basic_058',
    kanji: '書',
    reading: 'か',
    contextBefore: 'ノートに字を ',
    contextAfter: ' きます。',
    hint: '筆で重ねて書くような形だよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_059',
    kanji: '話',
    reading: 'はな',
    contextBefore: '友だちと ',
    contextAfter: ' します。',
    hint: '言べんの右に舌を書くよ。',
    strokeCount: 13,
  },
  {
    id: 'k_basic_060',
    kanji: '言',
    reading: 'い',
    contextBefore: '思ったことを ',
    contextAfter: ' います。',
    hint: '点と横線、口の形を整えよう。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_061',
    kanji: '計',
    reading: 'けい',
    contextBefore: '算数で ',
    contextAfter: ' 算をします。',
    hint: '言べんの右に十を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_062',
    kanji: '算',
    reading: 'さん',
    contextBefore: ' ',
    contextAfter: ' 数の問題をときます。',
    hint: '竹かんむりの下に目と廾を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k_basic_063',
    kanji: '数',
    reading: 'かず',
    contextBefore: 'りんごの ',
    contextAfter: ' を数えます。',
    hint: '左側と右側のバランスに気をつけよう。',
    strokeCount: 13,
  },
  {
    id: 'k_basic_064',
    kanji: '答',
    reading: 'こた',
    contextBefore: '問題の ',
    contextAfter: ' えを書きます。',
    hint: '竹かんむりの下に合を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k_basic_065',
    kanji: '考',
    reading: 'かんが',
    contextBefore: 'よく ',
    contextAfter: ' えてから答えます。',
    hint: '者に似た上部分と、下の形に気をつけよう。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_066',
    kanji: '知',
    reading: 'し',
    contextBefore: '新しいことを ',
    contextAfter: ' ります。',
    hint: '矢の右に口を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_067',
    kanji: '理',
    reading: 'り',
    contextBefore: '道 ',
    contextAfter: ' を考えて説明します。',
    hint: '王へんの右に里を書くよ。',
    strokeCount: 11,
  },
  {
    id: 'k_basic_068',
    kanji: '科',
    reading: 'か',
    contextBefore: '理 ',
    contextAfter: ' の実験をします。',
    hint: '禾へんの右に斗を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_069',
    kanji: '活',
    reading: 'かつ',
    contextBefore: '元気に生 ',
    contextAfter: ' します。',
    hint: 'さんずいの右に舌を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_070',
    kanji: '毎',
    reading: 'まい',
    contextBefore: ' ',
    contextAfter: ' 日、少しずつ練習します。',
    hint: '上に短い線、下に母を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_071',
    kanji: '朝',
    reading: 'あさ',
    contextBefore: ' ',
    contextAfter: ' ごはんを食べます。',
    hint: '左は十と日など、右は月を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k_basic_072',
    kanji: '昼',
    reading: 'ひる',
    contextBefore: ' ',
    contextAfter: ' 休みに外で遊びます。',
    hint: '尺の下に日と一を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_073',
    kanji: '夜',
    reading: 'よる',
    contextBefore: ' ',
    contextAfter: ' は早くねます。',
    hint: 'なべぶたの下に人と夕を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_074',
    kanji: '外',
    reading: 'そと',
    contextBefore: '天気がいいので ',
    contextAfter: ' で遊びます。',
    hint: '夕の右にトを書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_075',
    kanji: '内',
    reading: 'うち',
    contextBefore: '家の ',
    contextAfter: ' に入ります。',
    hint: 'どうがまえの中に人を書くよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_076',
    kanji: '家',
    reading: 'いえ',
    contextBefore: '私の ',
    contextAfter: ' には犬がいます。',
    hint: 'うかんむりの下に豕を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k_basic_077',
    kanji: '室',
    reading: 'しつ',
    contextBefore: '教 ',
    contextAfter: ' で勉強します。',
    hint: 'うかんむりの下に至を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_078',
    kanji: '町',
    reading: 'まち',
    contextBefore: '住んでいる ',
    contextAfter: ' を歩きます。',
    hint: '田の右に丁を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_079',
    kanji: '村',
    reading: 'むら',
    contextBefore: '小さな ',
    contextAfter: ' に住んでいます。',
    hint: '木へんの右に寸を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_080',
    kanji: '市',
    reading: 'し',
    contextBefore: '新潟 ',
    contextAfter: ' に住んでいます。',
    hint: 'なべぶたの下に巾を書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_081',
    kanji: '東',
    reading: 'ひがし',
    contextBefore: '太陽は ',
    contextAfter: ' からのぼります。',
    hint: '木に日が入ったような形だよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_082',
    kanji: '西',
    reading: 'にし',
    contextBefore: '太陽は ',
    contextAfter: ' にしずみます。',
    hint: '一の下に四角い形を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_083',
    kanji: '南',
    reading: 'みなみ',
    contextBefore: 'あたたかい ',
    contextAfter: ' の島へ行きたいです。',
    hint: '十の下に囲みと羊に似た形を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_084',
    kanji: '北',
    reading: 'きた',
    contextBefore: '北海道は日本の ',
    contextAfter: ' にあります。',
    hint: '左右の形を向かい合わせに書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_085',
    kanji: '道',
    reading: 'みち',
    contextBefore: '学校へ行く ',
    contextAfter: ' を覚えます。',
    hint: 'しんにょうの中に首を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k_basic_086',
    kanji: '海',
    reading: 'うみ',
    contextBefore: '夏休みに ',
    contextAfter: ' へ行きます。',
    hint: 'さんずいの右に毎を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_087',
    kanji: '空',
    reading: 'そら',
    contextBefore: '青い ',
    contextAfter: ' を見上げます。',
    hint: 'あなかんむりの下に工を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_088',
    kanji: '雲',
    reading: 'くも',
    contextBefore: '白い ',
    contextAfter: ' がうかんでいます。',
    hint: '雨かんむりの下に云を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k_basic_089',
    kanji: '風',
    reading: 'かぜ',
    contextBefore: '強い ',
    contextAfter: ' がふきます。',
    hint: '外側の形と中の虫に似た形を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_090',
    kanji: '雨',
    reading: 'あめ',
    contextBefore: ' ',
    contextAfter: ' がふっています。',
    hint: '横線の下に四つの点を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_091',
    kanji: '鳥',
    reading: 'とり',
    contextBefore: '木の上に ',
    contextAfter: ' がいます。',
    hint: '点と横線の数をよく見て書こう。',
    strokeCount: 11,
  },
  {
    id: 'k_basic_092',
    kanji: '魚',
    reading: 'さかな',
    contextBefore: '川で ',
    contextAfter: ' が泳いでいます。',
    hint: '上からク、田、下の点を書くよ。',
    strokeCount: 11,
  },
  {
    id: 'k_basic_093',
    kanji: '犬',
    reading: 'いぬ',
    contextBefore: 'かわいい ',
    contextAfter: ' と散歩します。',
    hint: '大に点を一つ足すよ。',
    strokeCount: 4,
  },
  {
    id: 'k_basic_094',
    kanji: '虫',
    reading: 'むし',
    contextBefore: '草むらに ',
    contextAfter: ' がいます。',
    hint: '口の下にたて線と点を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k_basic_095',
    kanji: '草',
    reading: 'くさ',
    contextBefore: '庭に ',
    contextAfter: ' が生えています。',
    hint: 'くさかんむりの下に早を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k_basic_096',
    kanji: '林',
    reading: 'はやし',
    contextBefore: '木がたくさんある ',
    contextAfter: ' を歩きます。',
    hint: '木を二つならべて書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_097',
    kanji: '岩',
    reading: 'いわ',
    contextBefore: '山に大きな ',
    contextAfter: ' があります。',
    hint: '山の下に石を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k_basic_098',
    kanji: '石',
    reading: 'いし',
    contextBefore: '道に丸い ',
    contextAfter: ' が落ちています。',
    hint: '一とノの下に口を書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k_basic_099',
    kanji: '貝',
    reading: 'かい',
    contextBefore: '海で ',
    contextAfter: ' がらを拾います。',
    hint: '目の下に八を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k_basic_100',
    kanji: '米',
    reading: 'こめ',
    contextBefore: '田んぼで ',
    contextAfter: ' を作ります。',
    hint: '十字に点とはらいを足すよ。',
    strokeCount: 6,
  }

];
