import { Card, Badge, ArithmeticQuestion, KanjiQuestion } from './types';

export const DEFAULT_CARDS: Card[] = [
  // Normal Cards (10-30 coins value range)
  {
    id: 'n1',
    name: 'ピカポチ',
    rarity: 'N',
    description: 'いつも元気に飛び跳ねている、でんきネズミ。ほっぺたを触ると静電気がピリリと走るよ。勉強が大好き！',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n2',
    name: 'モリノコ',
    rarity: 'N',
    description: '森の奥深くに住んでいる葉っぱの妖精。読書が趣味で、漢字を覚えるのが得意なんだ。',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n3',
    name: 'ペンタロウ',
    rarity: 'N',
    description: 'お腹の星マークがチャームポイントのペンギン。算数の計算を始めるとスピードが止まらない！',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n4',
    name: 'コロリン',
    rarity: 'N',
    description: 'ころころ転がる不思議な岩石モンスター。数字の「0」が大好きで、わり算を応援してくれる。',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'n5',
    name: 'ウサノフ',
    rarity: 'N',
    description: 'ノートを抱えたウサギ。いつも勉強の予定をメモしている、しっかり者。',
    imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=200&auto=format&fit=crop&q=80',
  },
  // Rare Cards
  {
    id: 'r1',
    name: 'イナズマレオ',
    rarity: 'R',
    description: '雲の上を走る、雷の力を持つちいさなライオン。算数の「かけ算筆算」で稲妻のような速さを手に入れた！',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r2',
    name: 'ホシヨミフクロウ',
    rarity: 'R',
    description: '夜空の星を読んで未来を占うフクロウ。漢字の歴史をすべて知っている物知り博士。',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r3',
    name: 'アクアドフィン',
    rarity: 'R',
    description: 'きれいな水の世界を守るイルカ。分数の計算が得意で、ピザやケーキを等分するのが大好き。',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'r4',
    name: 'クリスタルキツネ',
    rarity: 'R',
    description: '結晶のような美しいしっぽを持つキツネ。集中力が高まると、体が青くきらめくよ。',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=200&auto=format&fit=crop&q=80',
  },
  // Super Rare Cards
  {
    id: 'sr1',
    name: 'フェニックス・マスタリー',
    rarity: 'SR',
    description: 'あきらめずに挑戦し続けた勉強者にのみ姿を現す不死鳥。すべてを包み込む暖かい光で満ちている。',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'sr2',
    name: 'ギャラクシードラゴン',
    rarity: 'SR',
    description: '銀河のエネルギーを宿した伝説のドラゴン。大きな数（億兆）を自由に操り、宇宙を旅する。',
    imageUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'sr3',
    name: 'エンプレス・サクラ',
    rarity: 'SR',
    description: '漢字の奥義を極めた美しい桜の精霊。流れるような筆さばきで、すべての漢字を美しく書き上げる。',
    imageUrl: 'https://images.unsplash.com/photo-1522441815192-d9f04eb0615c?w=200&auto=format&fit=crop&q=80',
  }
];

export const DEFAULT_BADGES: Badge[] = [
  {
    id: 'badge_1',
    name: 'はじめの一歩',
    description: '最初の勉強をクリアする',
    iconName: 'BookOpen',
    requiredStreak: 0,
    unlocked: false,
  },
  {
    id: 'badge_2',
    name: '3日連続の達人',
    description: '勉強を3日間連続でがんばる',
    iconName: 'Flame',
    requiredStreak: 3,
    unlocked: false,
  },
  {
    id: 'badge_3',
    name: '5日連続の英雄',
    description: '勉強を5日間連続でがんばる',
    iconName: 'Award',
    requiredStreak: 5,
    unlocked: false,
  },
  {
    id: 'badge_4',
    name: '1週間マスター',
    description: '勉強を7日間連続でがんばる',
    iconName: 'Trophy',
    requiredStreak: 7,
    unlocked: false,
  },
  {
    id: 'badge_5',
    name: 'コレクター',
    description: 'トレーディングカードを5枚以上集める',
    iconName: 'Grid',
    requiredStreak: 0,
    unlocked: false,
  }
];

// 3rd Grade Arithmetic Questions
export const ARITHMETIC_QUESTIONS: ArithmeticQuestion[] = [
  // わり算 (Division)
  {
    id: 'm1',
    num1: 24,
    num2: 4,
    operator: '÷',
    questionText: '24 ÷ 4 はいくつかな？（4のだんの九九を思い出してね）',
    correctAnswer: 6,
    options: [4, 5, 6, 8],
    hint: '「4に何をかけたら24になるかな？」と考えてみてね。',
  },
  {
    id: 'm2',
    num1: 35,
    num2: 5,
    operator: '÷',
    questionText: '35 ÷ 5 はいくつかな？',
    correctAnswer: 7,
    options: [5, 6, 7, 8],
    hint: '5の段の九九で、答えが35になるものをさがそう！',
  },
  {
    id: 'm3',
    num1: 48,
    num2: 8,
    operator: '÷',
    questionText: '48 ÷ 8 はいくつかな？',
    correctAnswer: 6,
    options: [5, 6, 7, 8],
    hint: '8 × [ ] = 48。あてはまる数字は何かな？',
  },
  {
    id: 'm4',
    num1: 0,
    num2: 9,
    operator: '÷',
    questionText: '0 ÷ 9 はいくつかな？（お菓子が0個のとき、9人で分けても…？）',
    correctAnswer: 0,
    options: [0, 1, 9, 3],
    hint: '何もないものを分けても、やっぱり0だね！',
  },

  // かけ算筆算 (Multiplication with carry over)
  {
    id: 'm5',
    num1: 23,
    num2: 3,
    operator: '×',
    questionText: '23 × 3 はいくつかな？（筆算のように、一の位から順番にかけてね）',
    correctAnswer: 69,
    options: [56, 63, 69, 72],
    hint: 'まず 3 × 3 = 9、つぎに 20 × 3 = 60 だから…？',
  },
  {
    id: 'm6',
    num1: 45,
    num2: 2,
    operator: '×',
    questionText: '45 × 2 はいくつかな？（繰り上がりに気をつけてね！）',
    correctAnswer: 90,
    options: [80, 85, 90, 95],
    hint: '5 × 2 = 10 で、1が繰り上がるよ。4 × 2 = 8に 1をたすと…？',
  },
  {
    id: 'm7',
    num1: 12,
    num2: 4,
    operator: '×',
    questionText: '12 × 4 はいくつかな？',
    correctAnswer: 48,
    options: [36, 44, 48, 52],
    hint: '2 × 4 = 8 と 10 × 4 = 40 をあわせよう。',
  },

  // あまりのあるわり算 (Division with remainder)
  {
    id: 'm8',
    num1: 17,
    num2: 3,
    operator: '÷',
    questionText: '17 ÷ 3 の「商（しょう＝答えの数）」はいくつかな？',
    correctAnswer: 5,
    options: [4, 5, 6, 7],
    hint: '3のだんで17をこえない一番大きい数をさがそう。3 × 5 = 15、3 × 6 = 18。',
  },

  // 大きな数 (Large numbers)
  {
    id: 'm9',
    num1: 8000,
    num2: 2000,
    operator: '+',
    questionText: '8000 ＋ 2000 はいくつかな？',
    correctAnswer: 10000,
    options: [9000, 10000, 11000, 12000],
    hint: '「8000」に「2000」をたすと、1万（一万）になるよ。ゼロの数に気をつけよう！',
  },

  // 小数・分数 (Decimals & Fractions)
  {
    id: 'm10',
    num1: 3, // representing 0.3 + 0.4
    num2: 4,
    operator: '+',
    questionText: '0.3 ＋ 0.4 はいくつかな？',
    correctAnswer: 7, // will map to 0.7
    options: [1, 5, 7, 9], // maps to 0.1, 0.5, 0.7, 0.9 in UI
    hint: '0.1が、3個と4個あるから、あわせて何個かな？',
  }
];

// 3rd Grade Kanji Questions
export const KANJI_QUESTIONS: KanjiQuestion[] = [
  {
    id: 'k1',
    kanji: '赤',
    reading: 'あか',
    contextBefore: 'ポストは ',
    contextAfter: ' い色をしています。',
    hint: '「土」の下に「八」のような形を書くよ。赤（あか）信号の「あか」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k2',
    kanji: '青',
    reading: 'あお',
    contextBefore: 'さわやかに晴れた ',
    contextAfter: ' 空がひろがっている。',
    hint: '上は「ま（キ）」、下は「月」だよ。青（あお）色の「あお」だね。',
    strokeCount: 8,
  },
  {
    id: 'k3',
    kanji: '歌',
    reading: 'うた',
    contextBefore: 'みんなで元気に ',
    contextAfter: ' をうたいましょう。',
    hint: '左側は「可」をたてに2つ並べて、右側は「欠」を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k4',
    kanji: '森',
    reading: 'もり',
    contextBefore: 'たくさんの木が生いしげる ',
    contextAfter: ' の中をさんぽする。',
    hint: '「木」という漢字を、上に1つ、下に2つ、合計3つ書んだ！',
    strokeCount: 12,
  },
  {
    id: 'k5',
    kanji: '駅',
    reading: 'えき',
    contextBefore: '電車に乗るために ',
    contextAfter: ' まで歩いていきました。',
    hint: '左側は「馬（うまへん）」、右側は「尺」を書くよ。電車の「えき」だね。',
    strokeCount: 14,
  },
  {
    id: 'k6',
    kanji: '花',
    reading: 'はな',
    contextBefore: '庭にきれいな ',
    contextAfter: ' がさきました。',
    hint: '上は「くさかんむり」、下は「化」という漢字を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k7',
    kanji: '寺',
    reading: 'てら',
    contextBefore: '古いお ',
    contextAfter: ' で鐘（かね）の音がひびく。',
    hint: '上は「土」、下は「寸」を書くよ。お「てら」の漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k8',
    kanji: '走',
    reading: 'はし',
    contextBefore: '校庭を全力で ',
    contextAfter: ' る練習をします。',
    hint: '「土」の下に、走る足の形（「止」に似た形）を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k9',
    kanji: '茶',
    reading: 'ちゃ',
    contextBefore: '温かい緑 ',
    contextAfter: ' を飲んでほっとする。',
    hint: '上は「くさかんむり」、中は「人」のような形、下は「ホ」だよ。',
    strokeCount: 9,
  },
  {
    id: 'k10',
    kanji: '重',
    reading: 'おも',
    contextBefore: 'このダンボールはとても ',
    contextAfter: ' いです。',
    hint: '「千」と「里」が組み合わさったような漢字だよ。たいじゅうの「じゅう」でもあるよ。',
    strokeCount: 9,
  },
  {
    id: 'k11',
    kanji: '葉',
    reading: 'は',
    contextBefore: '秋になると、木の',
    contextAfter: 'が赤や黄色になります。',
    hint: '上は「くさかんむり」、中は「世」、下は「木」を書くよ。',
    strokeCount: 12,
  },
  {
    id: 'k12',
    kanji: '起',
    reading: 'お',
    contextBefore: '朝は早く',
    contextAfter: 'きて、あさごはんを食べましょう。',
    hint: '左側は「走」、右側は「己（おのれ）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k13',
    kanji: '速',
    reading: 'はや',
    contextBefore: '新幹線はとても',
    contextAfter: 'い乗り物です。',
    hint: 'しんにょうの中に「束（たば）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k14',
    kanji: '面',
    reading: 'めん',
    contextBefore: 'テレビのおもしろい画',
    contextAfter: 'をながめる。',
    hint: '一番上は「一」で、その下には目のような形を囲んで書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k15',
    kanji: '向',
    reading: 'む',
    contextBefore: 'あちらの',
    contextAfter: 'こうに見えるのが富士山です。',
    hint: '「の」の下に「冂」と「口」を書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k16',
    kanji: '緑',
    reading: 'みどり',
    contextBefore: '森にはたくさんの',
    contextAfter: 'があふれています。',
    hint: '左側は「糸（いとへん）」、右側は「彔」を書くよ。みどり色の漢字だよ。',
    strokeCount: 14,
  },
  {
    id: 'k17',
    kanji: '感',
    reading: 'かん',
    contextBefore: 'テストが終わって、ホッとした',
    contextAfter: 'じがする。',
    hint: '「咸」の下に「心」を組みあわせた漢字だよ。',
    strokeCount: 13,
  },
  {
    id: 'k18',
    kanji: '豆',
    reading: 'まめ',
    contextBefore: '節分の日には、お',
    contextAfter: 'まきをして鬼を退治します。',
    hint: '一番上は「一」、中は「口」、下は「ソ」に「一」を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k19',
    kanji: '物',
    reading: 'もの',
    contextBefore: 'スーパーへ買い',
    contextAfter: 'に行きます。',
    hint: '左側は「牛（うしへん）」、右側は「勿」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k20',
    kanji: '様',
    reading: 'さま',
    contextBefore: 'お殿',
    contextAfter: 'のような立派な服を着ています。',
    hint: '左側は「木（きへん）」、右側は「羊」の下に美の下半分のような形だよ。',
    strokeCount: 14,
  },
  {
    id: 'k21',
    kanji: '仕',
    reading: 'し',
    contextBefore: 'お父さんのお',
    contextAfter: 'ごとをおうえんする。',
    hint: '左側は「人（にんべん）」、右側は「士」を書くよ。仕事の「し」だよ。',
    strokeCount: 5,
  },
  {
    id: 'k22',
    kanji: '練',
    reading: 'れん',
    contextBefore: 'ピアノの習い事の',
    contextAfter: '習（しゅう）をがんばる。',
    hint: '左側は「糸（いとへん）」、右側は「東」を書くよ。',
    strokeCount: 14,
  },
  {
    id: 'k23',
    kanji: '習',
    reading: 'なら',
    contextBefore: '先生に漢字の正しい書き方を',
    contextAfter: 'う。',
    hint: '上は「羽」、下は「白」を組み合わせた漢字だよ。',
    strokeCount: 11,
  },
  {
    id: 'k24',
    kanji: '州',
    reading: 'しゅう',
    contextBefore: '私たちの住む本',
    contextAfter: 'は、日本で一番大きな島です。',
    hint: '「川」の中に点が3つ入るイメージで書くよ。',
    strokeCount: 6,
  },
  {
    id: 'k25',
    kanji: '央',
    reading: 'おう',
    contextBefore: '校庭の中',
    contextAfter: 'にみんなで大きな丸をつくる。',
    hint: '「大」の上の部分に四角い囲みが入る形だよ。',
    strokeCount: 5,
  },
  {
    id: 'k26',
    kanji: '横',
    reading: 'よこ',
    contextBefore: '信号のない道路を',
    contextAfter: 'ぎるときは左右を確認しよう。',
    hint: '左側は「木」、右側は「黄（きいろ）」を書くよ。',
    strokeCount: 15,
  },
  {
    id: 'k27',
    kanji: '倍',
    reading: 'ばい',
    contextBefore: 'ゲームの得点が二',
    contextAfter: 'になって大よろこび！',
    hint: '左側は「人（にんべん）」、右側は「咅（立の下に口）」を書くよ。',
    strokeCount: 10,
  },
  {
    id: 'k28',
    kanji: '館',
    reading: 'かん',
    contextBefore: '学校の図書',
    contextAfter: 'で面白い絵本をかりる。',
    hint: '左側は「食（しょくへん）」、右側は「官」を書くよ。',
    strokeCount: 16,
  },
  {
    id: 'k29',
    kanji: '事',
    reading: 'こと',
    contextBefore: '今日あったでき',
    contextAfter: 'を日記に書き残す。',
    hint: '「一」の下に「口」を書き、縦に貫き、最後に「フ」のようなハネだよ。',
    strokeCount: 8,
  },
  {
    id: 'k30',
    kanji: '号',
    reading: 'ごう',
    contextBefore: '青信',
    contextAfter: 'になったら横断歩道をわたります。',
    hint: '「口」の下に「丂（ひらがなの「て」に似た形）」を書くよ。',
    strokeCount: 5,
  },
  {
    id: 'k31',
    kanji: '使',
    reading: 'つか',
    contextBefore: 'お箸（はし）を上手に',
    contextAfter: 'ってごはんを食べましょう。',
    hint: '左側は「人（にんべん）」、右側は「吏」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k32',
    kanji: '意',
    reading: 'い',
    contextBefore: 'みんなの前で自分の',
    contextAfter: '見を発表します。',
    hint: '上に「音」、下に「心」を組み合わせた漢字だよ。',
    strokeCount: 13,
  },
  {
    id: 'k33',
    kanji: '味',
    reading: 'あじ',
    contextBefore: 'お母さんが作ったスープの',
    contextAfter: 'をみる。',
    hint: '左側は「口（くちへん）」、右側は「未」を書くよ。「末」と間違えないでね。',
    strokeCount: 8,
  },
  {
    id: 'k34',
    kanji: '漢',
    reading: 'かん',
    contextBefore: 'まいにちコツコツ',
    contextAfter: '字の練習をつづけよう。',
    hint: '左は「さんずい」、右は「廿（くさかんむり）」の下に「夫」を書くよ。',
    strokeCount: 13,
  },
  {
    id: 'k35',
    kanji: '表',
    reading: 'あらわ',
    contextBefore: '心の中の気持ちを絵に',
    contextAfter: 'してみよう。',
    hint: '「三」のような横線に「土」を組みあわせ、下は「衣」のようだよ。',
    strokeCount: 8,
  },
  {
    id: 'k36',
    kanji: '調',
    reading: 'しら',
    contextBefore: '辞書をひいて、わからない言葉を',
    contextAfter: 'べる。',
    hint: '左側は「言（ごんべん）」、右側は「周」を書くよ。',
    strokeCount: 15,
  },
  {
    id: 'k37',
    kanji: '柱',
    reading: 'はしら',
    contextBefore: 'このお寺には、とても太い',
    contextAfter: 'があります。',
    hint: '左側は「木」、右側は「主（ぬし）」を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k38',
    kanji: '所',
    reading: 'ところ',
    contextBefore: '秘密のば',
    contextAfter: 'に宝物をかくしておこう。',
    hint: '左側は「戸」、右側は「斤（おのづくり）」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k39',
    kanji: '持',
    reading: 'も',
    contextBefore: 'お気に入りのノートを手に',
    contextAfter: 'って出かける。',
    hint: '左側は「手（てへん）」、右側は「寺」を書くよ。',
    strokeCount: 9,
  },
  {
    id: 'k40',
    kanji: '局',
    reading: 'きょく',
    contextBefore: 'ハガキを出すために郵便',
    contextAfter: 'へ行きます。',
    hint: '「尸（しかばね）」の中に「句」が入る形だよ。',
    strokeCount: 7,
  },
  {
    id: 'k41',
    kanji: '配',
    reading: 'くば',
    contextBefore: '先生がみんなにプリントを',
    contextAfter: 'るのを手伝います。',
    hint: '左側は「酉」、右側は「己」を書くよ。配達（はいたつ）の「はい」だよ。',
    strokeCount: 10,
  },
  {
    id: 'k42',
    kanji: '住',
    reading: 'す',
    contextBefore: '緑豊かなすてきな町に',
    contextAfter: 'む。',
    hint: '左側は「人（にんべん）」、右側は「主」を書くよ。',
    strokeCount: 7,
  },
  {
    id: 'k43',
    kanji: '身',
    reading: 'み',
    contextBefore: '出かける前に、',
    contextAfter: 'じたくを整えましょう。',
    hint: '自分のからだを表す漢字だよ。中の右上に飛び出すハネに注意してね。',
    strokeCount: 7,
  },
  {
    id: 'k44',
    kanji: '育',
    reading: 'そだ',
    contextBefore: '朝顔の種をまいて、大切に',
    contextAfter: 'てる。',
    hint: '上は「充」の上半分のような形、下は「月」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k45',
    kanji: '守',
    reading: 'まも',
    contextBefore: '大切な約束はかならず',
    contextAfter: 'りましょう。',
    hint: '上は「うかんむり」、下は「寸」を書くよ。守る（まもる）の漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k46',
    kanji: '決',
    reading: 'き',
    contextBefore: '今日のおやつをどっちにするか',
    contextAfter: 'める。',
    hint: '左は「さんずい」、右は「夬」を書くよ。決定（けってい）の「けつ」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k47',
    kanji: '動',
    reading: 'うご',
    contextBefore: 'ゼンマイを巻くと、おもちゃが',
    contextAfter: 'きだします。',
    hint: '左側は「重」、右側は「力」を組み合わせた漢字だよ。',
    strokeCount: 11,
  },
  {
    id: 'k48',
    kanji: '問',
    reading: 'とい',
    contextBefore: '教科書にかかれている',
    contextAfter: 'に答えましょう。',
    hint: '「門（もんがまえ）」の中に「口」を書くよ。質問（しつもん）の「もん」だよ。',
    strokeCount: 11,
  },
  {
    id: 'k49',
    kanji: '題',
    reading: 'だい',
    contextBefore: '算数のむずかしい問',
    contextAfter: 'に挑戦してみる。',
    hint: '左は「是」、右は「頁（おおがい）」を組みあわせた漢字だよ。',
    strokeCount: 18,
  },
  {
    id: 'k50',
    kanji: '部',
    reading: 'ぶ',
    contextBefore: '自分の',
    contextAfter: '屋をお掃除してすっきりさせる。',
    hint: '左は「立」の下に「口」、右は「おおざと（阝）」を書くよ。',
    strokeCount: 11,
  },
  {
    id: 'k51',
    kanji: '筆',
    reading: 'ふで',
    contextBefore: '書道の時間には、',
    contextAfter: 'にすみをつけて文字を書きます。',
    hint: '上は「たけかんむり」、下は「聿（ふで）」を書くよ。鉛筆の「ひつ」だよ。',
    strokeCount: 12,
  },
  {
    id: 'k52',
    kanji: '者',
    reading: 'もの',
    contextBefore: 'このレースで一番速い',
    contextAfter: 'が優勝します。',
    hint: '「土」の下に「ノ」を斜めに引き、その下に「日」を書くよ。',
    strokeCount: 8,
  },
  {
    id: 'k53',
    kanji: '都',
    reading: 'と',
    contextBefore: '日本の首',
    contextAfter: 'は、美しい東京です。',
    hint: '左は「者」、右は「おおざと（阝）」を書くよ。京都や首都の「と」だよ。',
    strokeCount: 11,
  },
  {
    id: 'k54',
    kanji: '氷',
    reading: 'こおり',
    contextBefore: 'ジュースに冷たい',
    contextAfter: 'を浮かべて飲む。',
    hint: '「水」の左上の部分に、ちょんと点（「丶」）を1つ付け足すよ。',
    strokeCount: 5,
  },
  {
    id: 'k55',
    kanji: '泳',
    reading: 'およ',
    contextBefore: '夏の体育の授業では、プールで',
    contextAfter: 'ぎます。',
    hint: '左側は「さんずい」、右側は「永」を書くよ。水泳の「えい」だよ。',
    strokeCount: 8,
  },
  {
    id: 'k56',
    kanji: '有',
    reading: 'ゆう',
    contextBefore: '世界的に',
    contextAfter: '名な絵画を美術館で見る。',
    hint: '「𠂇（ナの形）」の下に、「月」を組みあわせた漢字だよ。',
    strokeCount: 6,
  },
  {
    id: 'k57',
    kanji: '返',
    reading: 'かえ',
    contextBefore: '図書館でかりた本を期日までに',
    contextAfter: 'す。',
    hint: 'しんにょうの中に「反」を書くよ。お返事の「へん」だよ。',
    strokeCount: 7,
  },
  {
    id: 'k58',
    kanji: '遊',
    reading: 'あそ',
    contextBefore: '放課後は公園で友達と元気いっぱいに',
    contextAfter: 'ぶ。',
    hint: 'しんにょうの中に「汓」と「方」のような形を組み合わせた漢字だよ。',
    strokeCount: 12,
  },
  {
    id: 'k59',
    kanji: '開',
    reading: 'あ',
    contextBefore: '窓をいっぱいに',
    contextAfter: 'けて、新鮮な空気を取り入れよう。',
    hint: '「門（もんがまえ）」の中に「一」と「开（鳥居のような形）」を書くよ。',
    strokeCount: 12,
  }
];
